package com.wmi.report_generator_service.dto;

import lombok.Data;

import java.util.HashMap;
import java.util.Map;

import static java.util.Optional.ofNullable;

@Data
public class PdfXRayOitReportDTO {

    private String funcao;
    private String logo;
    private String parceiro;
    private String endereco;
    private String localidade;
    private String telefone;
    private String qrcode;
    private String validador;
    private String especialidade;
    private String paciente;
    private String nascimento;
    private String sexo;
    private String medicoSolicitante;
    private String tecnicoResponsavel;
    private String rg;
    private String cpf;
    private String controle;
    private String indicacao;
    private String dataExame;
    private String empresa;
    private String site;
    private String carimbo;
    private String medico;
    private String matricula;
    private String data;
    private String hora;
    private String token;
    private String watermark;
    private String secao0RaioxDigital;
    private String secao0LeituraNegatoscopio;
    private String secao1AQualidadeTecnica;
    private String secao1AQualidadeTecnicaComentario;
    private String secao1BRadiografiaNormal;
    private String secao2AAnormalidadeParenquima;
    private String secao2BPequenasOpacidadesFormaTamanhoPrimaria;
    private String secao2BPequenasOpacidadesFormaTamanhoSecundaria;
    private String secao2BPequenasOpacidadesZonasD1;
    private String secao2BPequenasOpacidadesZonasD2;
    private String secao2BPequenasOpacidadesZonasD3;
    private String secao2BPequenasOpacidadesZonasE1;
    private String secao2BPequenasOpacidadesZonasE3;
    private String secao2BPequenasOpacidadesZonasE2;
    private String secao2BPequenasOpacidadesProfusao;
    private String secao2CGrandesOpacidades;
    private String secao3AAnormalidadePleural;
    private String secao3BPlacasPleurais;
    private String secao3BPlacasPleuraisLocalParedeEmPerfil0;
    private String secao3BPlacasPleuraisLocalParedeEmPerfilD;
    private String secao3BPlacasPleuraisLocalParedeEmPerfilE;
    private String secao3BPlacasPleuraisLocalFrontal0;
    private String secao3BPlacasPleuraisLocalFrontalD;
    private String secao3BPlacasPleuraisLocalFrontalE;
    private String secao3BPlacasPleuraisLocalDiafragma0;
    private String secao3BPlacasPleuraisLocalDiafragmaD;
    private String secao3BPlacasPleuraisLocalDiafragmaE;
    private String secao3BPlacasPleuraisLocalOutrosLocais0;
    private String secao3BPlacasPleuraisLocalOutrosLocaisD;
    private String secao3BPlacasPleuraisLocalOutrosLocaisE;
    private String secao3BPlacasPleuraisCalcificacaoParedeEmPerfil0;
    private String secao3BPlacasPleuraisCalcificacaoParedeEmPerfilD;
    private String secao3BPlacasPleuraisCalcificacaoParedeEmPerfilE;
    private String secao3BPlacasPleuraisCalcificacaoFrontal0;
    private String secao3BPlacasPleuraisCalcificacaoFrontalD;
    private String secao3BPlacasPleuraisCalcificacaoFrontalE;
    private String secao3BPlacasPleuraisCalcificacaoDiafragma0;
    private String secao3BPlacasPleuraisCalcificacaoDiafragmaD;
    private String secao3BPlacasPleuraisCalcificacaoDiafragmaE;
    private String secao3BPlacasPleuraisCalcificacaoOutrosLocais0;
    private String secao3BPlacasPleuraisCalcificacaoOutrosLocaisD;
    private String secao3BPlacasPleuraisCalcificacaoOutrosLocaisE;
    private String secao3BPlacasPleuraisExtensaoParedeEmPerfil0;
    private String secao3BPlacasPleuraisExtensaoParedeEmPerfilD;
    private String secao3BPlacasPleuraisExtensaoParedeEmPerfil1;
    private String secao3BPlacasPleuraisExtensaoParedeEmPerfil2;
    private String secao3BPlacasPleuraisExtensaoParedeEmPerfil3;
    private String secao3BPlacasPleuraisExtensaoFrontal0;
    private String secao3BPlacasPleuraisExtensaoFrontalD;
    private String secao3BPlacasPleuraisExtensaoFrontal1;
    private String secao3BPlacasPleuraisExtensaoFrontal2;
    private String secao3BPlacasPleuraisExtensaoFrontal3;
    private String secao3BPlacasPleuraisLarguraParedeEmPerfilD;
    private String secao3BPlacasPleuraisLarguraParedeEmPerfilA;
    private String secao3BPlacasPleuraisLarguraParedeEmPerfilB;
    private String secao3BPlacasPleuraisLarguraParedeEmPerfilC;
    private String secao3BPlacasPleuraisLarguraFrontalE;
    private String secao3BPlacasPleuraisLarguraFrontalA;
    private String secao3BPlacasPleuraisLarguraFrontalB;
    private String secao3BPlacasPleuraisLarguraFrontalC;
    private String secao3CObliteracaoSeioCostofrenico0;
    private String secao3CObliteracaoSeioCostofrenicoD;
    private String secao3CObliteracaoSeioCostofrenicoE;
    private String secao3DEspessamentoPleural;
    private String secao3DEspessamentoPleuralLocalParedeEmPerfil0;
    private String secao3DEspessamentoPleuralLocalParedeEmPerfilD;
    private String secao3DEspessamentoPleuralLocalParedeEmPerfilE;
    private String secao3DEspessamentoPleuralLocalFrontal0;
    private String secao3DEspessamentoPleuralLocalFrontalD;
    private String secao3DEspessamentoPleuralLocalFrontalE;
    private String secao3DEspessamentoPleuralCalcificacaoParedeEmPerfil0;
    private String secao3DEspessamentoPleuralCalcificacaoParedeEmPerfilD;
    private String secao3DEspessamentoPleuralCalcificacaoParedeEmPerfilE;
    private String secao3DEspessamentoPleuralCalcificacaoFrontal0;
    private String secao3DEspessamentoPleuralCalcificacaoFrontalD;
    private String secao3DEspessamentoPleuralCalcificacaoFrontalE;
    private String secao3DEspessamentoPleuralExtensaoParedeEmPerfil0;
    private String secao3DEspessamentoPleuralExtensaoParedeEmPerfilD;
    private String secao3DEspessamentoPleuralExtensaoParedeEmPerfil1;
    private String secao3DEspessamentoPleuralExtensaoParedeEmPerfil2;
    private String secao3DEspessamentoPleuralExtensaoParedeEmPerfil3;
    private String secao3DEspessamentoPleuralExtensaoFrontal0;
    private String secao3DEspessamentoPleuralExtensaoFrontalE;
    private String secao3DEspessamentoPleuralExtensaoFrontal1;
    private String secao3DEspessamentoPleuralExtensaoFrontal2;
    private String secao3DEspessamentoPleuralExtensaoFrontal3;
    private String secao3DEspessamentoPleuralLarguraParedeEmPerfilD;
    private String secao3DEspessamentoPleuralLarguraParedeEmPerfilA;
    private String secao3DEspessamentoPleuralLarguraParedeEmPerfilB;
    private String secao3DEspessamentoPleuralLarguraParedeEmPerfilC;
    private String secao3DEspessamentoPleuralLarguraFrontalE;
    private String secao3DEspessamentoPleuralLarguraFrontalA;
    private String secao3DEspessamentoPleuralLarguraFrontalB;
    private String secao3DEspessamentoPleuralLarguraFrontalC;
    private String secao4AOutrasAnormalidades;
    private String secao4CComentarios;
    private String secao3BPlacasPleuraisDiafragma0;
    private String secao3BPlacasPleuraisOutrosLocaisD;
    private String secao3BPlacasPleuraisDiafragmaD;
    private String secao3BPlacasPleuraisDiafragmaE;
    private String secao3BPlacasPleuraisOutrosLocaisE;
    private String secao3BPlacasPleuraisOutrosLocais0;
    private String secao3BPlacasPleuraisExtensaoFrontalE;
    private String aa;
    private String at;
    private String ax;
    private String bu;
    private String ca;
    private String cg;
    private String cn;
    private String co;
    private String cp;
    private String cv;
    private String di;
    private String ef;
    private String em;
    private String es;
    private String fr;
    private String hi;
    private String ho;
    private String id;
    private String ih;
    private String kl;
    private String me;
    private String pa;
    private String pb;
    private String pi;
    private String px;
    private String ra;
    private String rp;
    private String tb;
    private String od;


    public Map<String, String> getAttributes() {
        Map<String, String> attributes = new HashMap<>();
        ofNullable(funcao).ifPresent(value -> attributes.put("funcao", funcao));
        ofNullable(logo).ifPresent(value -> attributes.put("logo", logo));
        ofNullable(parceiro).ifPresent(value -> attributes.put("parceiro", parceiro));
        ofNullable(endereco).ifPresent(value -> attributes.put("endereco", endereco));
        ofNullable(localidade).ifPresent(value -> attributes.put("localidade", localidade));
        ofNullable(telefone).ifPresent(value -> attributes.put("telefone", telefone));
        ofNullable(qrcode).ifPresent(value -> attributes.put("qrcode", qrcode));
        ofNullable(validador).ifPresent(value -> attributes.put("validador", validador));
        ofNullable(especialidade).ifPresent(value -> attributes.put("especialidade", especialidade));
        ofNullable(paciente).ifPresent(value -> attributes.put("paciente", paciente));
        ofNullable(nascimento).ifPresent(value -> attributes.put("nascimento", nascimento));
        ofNullable(sexo).ifPresent(value -> attributes.put("sexo", sexo));
        ofNullable(medicoSolicitante).ifPresent(value -> attributes.put("medico_solicitante", medicoSolicitante));
        ofNullable(tecnicoResponsavel).ifPresent(value -> attributes.put("medico_responsavel", tecnicoResponsavel));
        ofNullable(sexo).ifPresent(value -> attributes.put("sexo", sexo));
        ofNullable(rg).ifPresent(value -> attributes.put("rg", rg));
        ofNullable(cpf).ifPresent(value -> attributes.put("cpf", cpf));
        ofNullable(controle).ifPresent(value -> attributes.put("controle", controle));
        ofNullable(indicacao).ifPresent(value -> attributes.put("indicacao", indicacao));
        ofNullable(dataExame).ifPresent(value -> attributes.put("dataExame", dataExame));
        ofNullable(empresa).ifPresent(value -> attributes.put("empresa", empresa));
        ofNullable(site).ifPresent(value -> attributes.put("site", site));
        ofNullable(carimbo).ifPresent(value -> attributes.put("carimbo", carimbo));
        ofNullable(medico).ifPresent(value -> attributes.put("medico", medico));
        ofNullable(matricula).ifPresent(value -> attributes.put("matricula", matricula));
        ofNullable(data).ifPresent(value -> attributes.put("data", data));
        ofNullable(hora).ifPresent(value -> attributes.put("hora", hora));
        ofNullable(token).ifPresent(value -> attributes.put("token", token));
        ofNullable(watermark).ifPresent(value -> attributes.put("watermark", watermark));
        ofNullable(secao0RaioxDigital).ifPresent(value -> attributes.put("secao_0_raiox_digital", secao0RaioxDigital));
        ofNullable(secao0LeituraNegatoscopio).ifPresent(value -> attributes.put("secao_0_leitura_negatoscopio", secao0LeituraNegatoscopio));
        ofNullable(secao1AQualidadeTecnica).ifPresent(value -> attributes.put("secao_1A_qualidade_tecnica", secao1AQualidadeTecnica));
        ofNullable(secao1AQualidadeTecnicaComentario).ifPresent(value -> attributes.put("secao_1A_qualidade_tecnica_comentario", secao1AQualidadeTecnicaComentario));
        ofNullable(secao1BRadiografiaNormal).ifPresent(value -> attributes.put("secao_1B_radiografia_normal", secao1BRadiografiaNormal));
        ofNullable(secao2AAnormalidadeParenquima).ifPresent(value -> attributes.put("secao_2A_anormalidade_parenquima", secao2AAnormalidadeParenquima));
        ofNullable(secao2BPequenasOpacidadesFormaTamanhoPrimaria).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_forma_tamanho_primaria", secao2BPequenasOpacidadesFormaTamanhoPrimaria));
        ofNullable(secao2BPequenasOpacidadesFormaTamanhoSecundaria).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_forma_tamanho_secundaria", secao2BPequenasOpacidadesFormaTamanhoSecundaria));
        ofNullable(secao2BPequenasOpacidadesZonasD1).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_zonas_d_1", secao2BPequenasOpacidadesZonasD1));
        ofNullable(secao2BPequenasOpacidadesZonasD2).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_zonas_d_2", secao2BPequenasOpacidadesZonasD2));
        ofNullable(secao2BPequenasOpacidadesZonasD3).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_zonas_d_3", secao2BPequenasOpacidadesZonasD3));
        ofNullable(secao2BPequenasOpacidadesZonasE1).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_zonas_e_1", secao2BPequenasOpacidadesZonasE1));
        ofNullable(secao2BPequenasOpacidadesZonasE2).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_zonas_e_3", secao2BPequenasOpacidadesZonasE2));
        ofNullable(secao2BPequenasOpacidadesZonasE3).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_zonas_e_2", secao2BPequenasOpacidadesZonasE3));
        ofNullable(secao2BPequenasOpacidadesProfusao).ifPresent(value -> attributes.put("secao_2B_pequenas_opacidades_profusao", secao2BPequenasOpacidadesProfusao));
        ofNullable(secao2CGrandesOpacidades).ifPresent(value -> attributes.put("secao_2C_grandes_opacidades", secao2CGrandesOpacidades));
        ofNullable(secao3AAnormalidadePleural).ifPresent(value -> attributes.put("secao_3A_anormalidade_pleural", secao3AAnormalidadePleural));
        ofNullable(secao3BPlacasPleurais).ifPresent(value -> attributes.put("secao_3B_placas_pleurais", secao3BPlacasPleurais));
        ofNullable(secao3BPlacasPleuraisLocalParedeEmPerfil0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_parede_em_perfil_0", secao3BPlacasPleuraisLocalParedeEmPerfil0));
        ofNullable(secao3BPlacasPleuraisLocalParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_parede_em_perfil_D", secao3BPlacasPleuraisLocalParedeEmPerfilD));
        ofNullable(secao3BPlacasPleuraisLocalParedeEmPerfilE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_parede_em_perfil_E", secao3BPlacasPleuraisLocalParedeEmPerfilE));
        ofNullable(secao3BPlacasPleuraisLocalFrontal0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_frontal_0", secao3BPlacasPleuraisLocalFrontal0));
        ofNullable(secao3BPlacasPleuraisLocalFrontalD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_frontal_D", secao3BPlacasPleuraisLocalFrontalD));
        ofNullable(secao3BPlacasPleuraisLocalFrontalE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_frontal_E", secao3BPlacasPleuraisLocalFrontalE));
        ofNullable(secao3BPlacasPleuraisLocalDiafragma0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_diafragma_0", secao3BPlacasPleuraisLocalDiafragma0));
        ofNullable(secao3BPlacasPleuraisLocalDiafragmaD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_diafragma_D", secao3BPlacasPleuraisLocalDiafragmaD));
        ofNullable(secao3BPlacasPleuraisLocalDiafragmaE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_diafragma_E", secao3BPlacasPleuraisLocalDiafragmaE));
        ofNullable(secao3BPlacasPleuraisLocalOutrosLocais0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_outros_locais_0", secao3BPlacasPleuraisLocalOutrosLocais0));
        ofNullable(secao3BPlacasPleuraisLocalOutrosLocaisD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_outros_locais_D", secao3BPlacasPleuraisLocalOutrosLocaisD));
        ofNullable(secao3BPlacasPleuraisLocalOutrosLocaisE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_local_outros_locais_E", secao3BPlacasPleuraisLocalOutrosLocaisE));
        ofNullable(secao3BPlacasPleuraisCalcificacaoParedeEmPerfil0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_parede_em_perfil_0", secao3BPlacasPleuraisCalcificacaoParedeEmPerfil0));
        ofNullable(secao3BPlacasPleuraisCalcificacaoParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_parede_em_perfil_D", secao3BPlacasPleuraisCalcificacaoParedeEmPerfilD));
        ofNullable(secao3BPlacasPleuraisCalcificacaoParedeEmPerfilE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_parede_em_perfil_E", secao3BPlacasPleuraisCalcificacaoParedeEmPerfilE));
        ofNullable(secao3BPlacasPleuraisCalcificacaoFrontal0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_frontal_0", secao3BPlacasPleuraisCalcificacaoFrontal0));
        ofNullable(secao3BPlacasPleuraisCalcificacaoFrontalD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_frontal_D", secao3BPlacasPleuraisCalcificacaoFrontalD));
        ofNullable(secao3BPlacasPleuraisCalcificacaoFrontalE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_frontal_E", secao3BPlacasPleuraisCalcificacaoFrontalE));
        ofNullable(secao3BPlacasPleuraisCalcificacaoDiafragma0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_diafragma_0", secao3BPlacasPleuraisCalcificacaoDiafragma0));
        ofNullable(secao3BPlacasPleuraisCalcificacaoDiafragmaD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_diafragma_D", secao3BPlacasPleuraisCalcificacaoDiafragmaD));
        ofNullable(secao3BPlacasPleuraisCalcificacaoDiafragmaE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_diafragma_E", secao3BPlacasPleuraisCalcificacaoDiafragmaE));
        ofNullable(secao3BPlacasPleuraisCalcificacaoOutrosLocais0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_outros_locais_0", secao3BPlacasPleuraisCalcificacaoOutrosLocais0));
        ofNullable(secao3BPlacasPleuraisCalcificacaoOutrosLocaisD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_outros_locais_D", secao3BPlacasPleuraisCalcificacaoOutrosLocaisD));
        ofNullable(secao3BPlacasPleuraisCalcificacaoOutrosLocaisE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_calcificacao_outros_locais_E", secao3BPlacasPleuraisCalcificacaoOutrosLocaisE));
        ofNullable(secao3BPlacasPleuraisExtensaoParedeEmPerfil0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_parede_em_perfil_0", secao3BPlacasPleuraisExtensaoParedeEmPerfil0));
        ofNullable(secao3BPlacasPleuraisExtensaoParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_parede_em_perfil_D", secao3BPlacasPleuraisExtensaoParedeEmPerfilD));
        ofNullable(secao3BPlacasPleuraisExtensaoParedeEmPerfil1).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_parede_em_perfil_1", secao3BPlacasPleuraisExtensaoParedeEmPerfil1));
        ofNullable(secao3BPlacasPleuraisExtensaoParedeEmPerfil2).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_parede_em_perfil_2", secao3BPlacasPleuraisExtensaoParedeEmPerfil2));
        ofNullable(secao3BPlacasPleuraisExtensaoParedeEmPerfil3).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_parede_em_perfil_3", secao3BPlacasPleuraisExtensaoParedeEmPerfil3));
        ofNullable(secao3BPlacasPleuraisExtensaoFrontal0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_frontal_0", secao3BPlacasPleuraisExtensaoFrontal0));
        ofNullable(secao3BPlacasPleuraisExtensaoFrontalD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_frontal_D", secao3BPlacasPleuraisExtensaoFrontalD));
        ofNullable(secao3BPlacasPleuraisExtensaoFrontal1).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_frontal_1", secao3BPlacasPleuraisExtensaoFrontal1));
        ofNullable(secao3BPlacasPleuraisExtensaoFrontal2).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_frontal_2", secao3BPlacasPleuraisExtensaoFrontal2));
        ofNullable(secao3BPlacasPleuraisExtensaoFrontal3).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_frontal_3", secao3BPlacasPleuraisExtensaoFrontal3));
        ofNullable(secao3BPlacasPleuraisLarguraParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_parede_em_perfil_D", secao3BPlacasPleuraisLarguraParedeEmPerfilD));
        ofNullable(secao3BPlacasPleuraisLarguraParedeEmPerfilA).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_parede_em_perfil_A", secao3BPlacasPleuraisLarguraParedeEmPerfilA));
        ofNullable(secao3BPlacasPleuraisLarguraParedeEmPerfilB).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_parede_em_perfil_B", secao3BPlacasPleuraisLarguraParedeEmPerfilB));
        ofNullable(secao3BPlacasPleuraisLarguraParedeEmPerfilC).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_parede_em_perfil_C", secao3BPlacasPleuraisLarguraParedeEmPerfilC));
        ofNullable(secao3BPlacasPleuraisLarguraFrontalE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_frontal_E", secao3BPlacasPleuraisLarguraFrontalE));
        ofNullable(secao3BPlacasPleuraisLarguraFrontalA).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_frontal_A", secao3BPlacasPleuraisLarguraFrontalA));
        ofNullable(secao3BPlacasPleuraisLarguraFrontalB).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_frontal_B", secao3BPlacasPleuraisLarguraFrontalB));
        ofNullable(secao3BPlacasPleuraisLarguraFrontalC).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_largura_frontal_C", secao3BPlacasPleuraisLarguraFrontalC));
        ofNullable(secao3CObliteracaoSeioCostofrenico0).ifPresent(value -> attributes.put("secao_3C_obliteracao_seio_costofrenico_0", secao3CObliteracaoSeioCostofrenico0));
        ofNullable(secao3CObliteracaoSeioCostofrenicoD).ifPresent(value -> attributes.put("secao_3C_obliteracao_seio_costofrenico_D", secao3CObliteracaoSeioCostofrenicoD));
        ofNullable(secao3CObliteracaoSeioCostofrenicoE).ifPresent(value -> attributes.put("secao_3C_obliteracao_seio_costofrenico_E", secao3CObliteracaoSeioCostofrenicoE));
        ofNullable(secao3DEspessamentoPleural).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural", secao3DEspessamentoPleural));
        ofNullable(secao3DEspessamentoPleuralLocalParedeEmPerfil0).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_local_parede_em_perfil_0", secao3DEspessamentoPleuralLocalParedeEmPerfil0));
        ofNullable(secao3DEspessamentoPleuralLocalParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_local_parede_em_perfil_D", secao3DEspessamentoPleuralLocalParedeEmPerfilD));
        ofNullable(secao3DEspessamentoPleuralLocalParedeEmPerfilE).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_local_parede_em_perfil_E", secao3DEspessamentoPleuralLocalParedeEmPerfilE));
        ofNullable(secao3DEspessamentoPleuralLocalFrontal0).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_local_frontal_0", secao3DEspessamentoPleuralLocalFrontal0));
        ofNullable(secao3DEspessamentoPleuralLocalFrontalD).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_local_frontal_D", secao3DEspessamentoPleuralLocalFrontalD));
        ofNullable(secao3DEspessamentoPleuralLocalFrontalE).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_local_frontal_E", secao3DEspessamentoPleuralLocalFrontalE));
        ofNullable(secao3DEspessamentoPleuralCalcificacaoParedeEmPerfil0).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_calcificacao_parede_em_perfil_0", secao3DEspessamentoPleuralCalcificacaoParedeEmPerfil0));
        ofNullable(secao3DEspessamentoPleuralCalcificacaoParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_calcificacao_parede_em_perfil_D", secao3DEspessamentoPleuralCalcificacaoParedeEmPerfilD));
        ofNullable(secao3DEspessamentoPleuralCalcificacaoParedeEmPerfilE).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_calcificacao_parede_em_perfil_E", secao3DEspessamentoPleuralCalcificacaoParedeEmPerfilE));
        ofNullable(secao3DEspessamentoPleuralCalcificacaoFrontal0).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_calcificacao_frontal_0", secao3DEspessamentoPleuralCalcificacaoFrontal0));
        ofNullable(secao3DEspessamentoPleuralCalcificacaoFrontalD).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_calcificacao_frontal_D", secao3DEspessamentoPleuralCalcificacaoFrontalD));
        ofNullable(secao3DEspessamentoPleuralCalcificacaoFrontalE).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_calcificacao_frontal_E", secao3DEspessamentoPleuralCalcificacaoFrontalE));
        ofNullable(secao3DEspessamentoPleuralExtensaoParedeEmPerfil0).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_parede_em_perfil_0", secao3DEspessamentoPleuralExtensaoParedeEmPerfil0));
        ofNullable(secao3DEspessamentoPleuralExtensaoParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_parede_em_perfil_D", secao3DEspessamentoPleuralExtensaoParedeEmPerfilD));
        ofNullable(secao3DEspessamentoPleuralExtensaoParedeEmPerfil1).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_parede_em_perfil_1", secao3DEspessamentoPleuralExtensaoParedeEmPerfil1));
        ofNullable(secao3DEspessamentoPleuralExtensaoParedeEmPerfil2).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_parede_em_perfil_2", secao3DEspessamentoPleuralExtensaoParedeEmPerfil2));
        ofNullable(secao3DEspessamentoPleuralExtensaoParedeEmPerfil3).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_parede_em_perfil_3", secao3DEspessamentoPleuralExtensaoParedeEmPerfil3));
        ofNullable(secao3DEspessamentoPleuralExtensaoFrontal0).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_frontal_0", secao3DEspessamentoPleuralExtensaoFrontal0));
        ofNullable(secao3DEspessamentoPleuralExtensaoFrontalE).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_frontal_E", secao3DEspessamentoPleuralExtensaoFrontalE));
        ofNullable(secao3DEspessamentoPleuralExtensaoFrontal1).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_frontal_1", secao3DEspessamentoPleuralExtensaoFrontal1));
        ofNullable(secao3DEspessamentoPleuralExtensaoFrontal2).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_frontal_2", secao3DEspessamentoPleuralExtensaoFrontal2));
        ofNullable(secao3DEspessamentoPleuralExtensaoFrontal3).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_extensao_frontal_3", secao3DEspessamentoPleuralExtensaoFrontal3));
        ofNullable(secao3DEspessamentoPleuralLarguraParedeEmPerfilD).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_parede_em_perfil_D", secao3DEspessamentoPleuralLarguraParedeEmPerfilD));
        ofNullable(secao3DEspessamentoPleuralLarguraParedeEmPerfilA).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_parede_em_perfil_A", secao3DEspessamentoPleuralLarguraParedeEmPerfilA));
        ofNullable(secao3DEspessamentoPleuralLarguraParedeEmPerfilB).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_parede_em_perfil_B", secao3DEspessamentoPleuralLarguraParedeEmPerfilB));
        ofNullable(secao3DEspessamentoPleuralLarguraParedeEmPerfilC).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_parede_em_perfil_C", secao3DEspessamentoPleuralLarguraParedeEmPerfilC));
        ofNullable(secao3DEspessamentoPleuralLarguraFrontalE).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_frontal_E", secao3DEspessamentoPleuralLarguraFrontalE));
        ofNullable(secao3DEspessamentoPleuralLarguraFrontalA).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_frontal_A", secao3DEspessamentoPleuralLarguraFrontalA));
        ofNullable(secao3DEspessamentoPleuralLarguraFrontalB).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_frontal_B", secao3DEspessamentoPleuralLarguraFrontalB));
        ofNullable(secao3DEspessamentoPleuralLarguraFrontalC).ifPresent(value -> attributes.put("secao_3D_espessamento_pleural_largura_frontal_C", secao3DEspessamentoPleuralLarguraFrontalC));
        ofNullable(secao4AOutrasAnormalidades).ifPresent(value -> attributes.put("secao_4A_outras_anormalidades", secao4AOutrasAnormalidades));
        ofNullable(secao4CComentarios).ifPresent(value -> attributes.put("secao_4C_comentarios", secao4CComentarios));
        ofNullable(secao3BPlacasPleuraisDiafragma0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_diafragma_0", secao3BPlacasPleuraisDiafragma0));
        ofNullable(secao3BPlacasPleuraisOutrosLocaisD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_outros_locais_D", secao3BPlacasPleuraisOutrosLocaisD));
        ofNullable(secao3BPlacasPleuraisDiafragmaD).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_diafragma_D", secao3BPlacasPleuraisDiafragmaD));
        ofNullable(secao3BPlacasPleuraisDiafragmaE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_outros_locais_E", secao3BPlacasPleuraisDiafragmaE));
        ofNullable(secao3BPlacasPleuraisOutrosLocaisE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_outros_locais_E", secao3BPlacasPleuraisOutrosLocaisE));
        ofNullable(secao3BPlacasPleuraisOutrosLocais0).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_outros_locais_0", secao3BPlacasPleuraisOutrosLocais0));
        ofNullable(secao3BPlacasPleuraisExtensaoFrontalE).ifPresent(value -> attributes.put("secao_3B_placas_pleurais_extensao_frontal_E", secao3BPlacasPleuraisExtensaoFrontalE));
        ofNullable(aa).ifPresent(value -> attributes.put("aa", aa));
        ofNullable(at).ifPresent(value -> attributes.put("at", at));
        ofNullable(ax).ifPresent(value -> attributes.put("ax", ax));
        ofNullable(bu).ifPresent(value -> attributes.put("bu", bu));
        ofNullable(ca).ifPresent(value -> attributes.put("ca", ca));
        ofNullable(cg).ifPresent(value -> attributes.put("cg", cg));
        ofNullable(cn).ifPresent(value -> attributes.put("cn", cn));
        ofNullable(co).ifPresent(value -> attributes.put("co", co));
        ofNullable(cp).ifPresent(value -> attributes.put("cp", cp));
        ofNullable(cv).ifPresent(value -> attributes.put("cv", cv));
        ofNullable(di).ifPresent(value -> attributes.put("di", di));
        ofNullable(ef).ifPresent(value -> attributes.put("ef", ef));
        ofNullable(em).ifPresent(value -> attributes.put("em", em));
        ofNullable(es).ifPresent(value -> attributes.put("es", es));
        ofNullable(fr).ifPresent(value -> attributes.put("fr", fr));
        ofNullable(hi).ifPresent(value -> attributes.put("hi", hi));
        ofNullable(ho).ifPresent(value -> attributes.put("ho", ho));
        ofNullable(id).ifPresent(value -> attributes.put("id", id));
        ofNullable(ih).ifPresent(value -> attributes.put("ih", ih));
        ofNullable(kl).ifPresent(value -> attributes.put("kl", kl));
        ofNullable(me).ifPresent(value -> attributes.put("me", me));
        ofNullable(pa).ifPresent(value -> attributes.put("pa", pa));
        ofNullable(pb).ifPresent(value -> attributes.put("pb", pb));
        ofNullable(pi).ifPresent(value -> attributes.put("pi", pi));
        ofNullable(px).ifPresent(value -> attributes.put("px", px));
        ofNullable(ra).ifPresent(value -> attributes.put("ra", ra));
        ofNullable(rp).ifPresent(value -> attributes.put("rp", rp));
        ofNullable(tb).ifPresent(value -> attributes.put("tb", tb));
        ofNullable(od).ifPresent(value -> attributes.put("od", od));

        return attributes;
    }
}
